language: python
# 3.3 not supported for testing: https://github.com/pytest-dev/py/issues/175
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev" # 3.8 development branch

install:
  - pip install -r test-requirements.txt

script:
  # need to add coverage support
  - pytest -vv xeger/tests
